// Edm Config Tools Actions
export const edmAction = {
  UPDATE_INPUT: "UPDATE_INPUT",
  HANDLE_CONTAINER: "HANDLE_CONTAINER",
  OPEN_CONFIG_IMG_DIALOG: "OPEN_CONFIG_IMG_DIALOG",
  CLOSE_CONFIG_IMG_DIALOG: "CLOSE_CONFIG_IMG_DIALOG",
  CONFIRM_CONFIG_IMG_DIALOG: "CONFIRM_CONFIG_IMG_DIALOG",
  UPDATE_DIALOG_INPUT: "UPDATE_DIALOG_INPUT",
  UPDATE_IMG_PREVIEWER_INPUT: "UPDATE_IMG_PREVIEWER_INPUT",
  UPDATE_IMG_PREVIEWER: "UPDATE_IMG_PREVIEWER",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",
};

// Code Snipper Manager Actions
export const csmAction = {
  OPEN_DIALOG: "OPEN_DIALOG",
  CLOSE_DIALOG: "CLOSE_DIALOG",
  UPDATE_CURR_LANG: "UPDATE_CURR_LANG",
};
